# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c110a71fe6a40125dd71f719c001cc797236e72fadcef45db504217deb2ea8faad2dfd7eda7acd914d9cc35f859c12303bb3ea04afbe2fe4bf960ae6d0f4bc1

test:
  secret_key_base: 6e383e577661abdc2d6034ec95974b1ecb51c13f498ead0e12cfd9b2874b4c680c0f5b0ba118c9bf69c52b9e33925337d9477a9cf684362b4aa9f3f55386978e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
